version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: bap
      POSTGRES_PASSWORD: bap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network
    ports:
      - "5432:5432"  # Expose PostgreSQL port

  admin:
    image: dpage/pgadmin4:latest
    environment: 
      PGADMIN_DEFAULT_EMAIL: baptiste.pouquerou@gmail.com
      PGADMIN_DEFAULT_PASSWORD: bap
    ports:
      - "5050:80"  # Map container port to host port for pgAdmin web interface
    depends_on:
      - db
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  postgres_data: